// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uaktcrxuuxyzjfssznde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVha3Rjcnh1dXh5empmc3N6bmRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyOTQ1MzYsImV4cCI6MjA3NDg3MDUzNn0.MPo4GkGEfg3ejIjvA8LLYDCIkTnD---PQz-5PWzDivw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});